### ISSUE TITLE
Duplicated filename problem

### ISSUE THREAD

**Issue by eight04** [Moeriki/temporarily#3]
If the file tree contains duplicated filename, it would fail to create the file tree in some cases. This would work:
```js
const {dir, file} = require("temporarily");
dir([
    dir([
        file({name: "foo.txt"})
    ]),
    file({name: "foo.txt"})
]);
```
https://runkit.com/embed/7z186vonwegw

This would not:
```js
const {dir, file} = require("temporarily");
dir([
    file({name: "foo.txt"}),
    dir([
        file({name: "foo.txt"})
    ])
]);
```
https://runkit.com/embed/agf3dwbmamjs

The first `foo.txt` is overwritten by the second `foo.txt`. I think:

1. The module should throw an error when a file is overwritten that it can't handle this situation.
2. Maybe adding an option `finalName`? which acts like a filename but it is only used in renaming (i.e. use a random name for creation), so the overwritten would never happen.

**Comment by moeriki** [comment]
The first `foo.txt` indead replaced the second one without warning. I still looking into adding that.

For the core issue I added an addition random directory on top of `os.tmpdir()` which more often than not returns just the same dir.
